--- #YAML:1.0
name:               String-LCSS_XS
version:            1.0_9
abstract:           Find The Longest Common Substring of Two Strings.
author:
    - Markus Riester <mriester@gmx.de>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Exporter:    0
    Test::More:  0
    XSLoader:    0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
